name: Docsbot Command Dispatch
on:
  issue_comment:
    types: [created]
jobs:
  dispatchCommand:
    runs-on: ubuntu-latest
    steps:
      # need to check out code to get config
      - uses: actions/checkout@v3

      - name: Environment
        run: env

      - uses: peter-evans/slash-command-dispatch@v3
        with:
          token: ${{ secrets.PAT }}
          reactions: false
          config-from-file: .github/docsbot-config.json